//
//  KS3ExceptionConstants.h
//  KS3YunSDK
//
//  Created by JackWong on 15/6/2.
//  Copyright (c) 2015年 kingsoft. All rights reserved.
//

#ifndef KS3YunSDK_KS3ExceptionConstants_h
#define KS3YunSDK_KS3ExceptionConstants_h

#define ERROR_CODE_UNKNOWN_ERROR (-1)
#define ERROR_CODE_BAD_DIGEST 0
#define ERROR_CODE_INVALID_ACL_STR 1
#define ERROR_CODE_INVALID_AUTHORIZATION_STR 2
#define ERROR_CODE_INVALID_BUCKET_NAME 3
#define ERROR_CODE_INVALID_DATE_FORMAT 4
#define ERROR_CODE_INVALID_DIGEST 5
#define ERROR_CODE_INVALID_ENCYPTION_ALGORITHM 6
#define ERROR_CODE_INVALID_HOST_HEADER 7
#define ERROR_CODE_INVALID_PARAMETER 8
#define ERROR_CODE_INVALID_PATH 9
#define ERROR_CODE_INVALID_QUERY_STR 10
#define ERROR_CODE_META_DATA_TOO_LARGE 11
#define ERROR_CODE_MISSING_DATA_HEADER 12
#define ERROR_CODE_MISSING_HOST_HEADER 13
#define ERROR_CODE_TOO_MANY_BUCKETS 14
#define ERROR_CODE_BAD_PARAMS 15
#define ERROR_CODE_IMAGE_TYPE_NOT_SUPPORT 16
#define ERROR_CODE_MISSING_FROM_ARGS 17
#define ERROR_CODE_CONTENT_RANGE_ERROR 18
#define ERROR_CODE_CONTENT_LENGTH_OUT_OF_RANGE 19
#define ERROR_CODE_POLICY_ERROR 20
#define ERROR_CODE_EXPIRATION_ERROR 21
#define ERROR_CODE_FORM_UNMATCH_POLICY 22
#define ERROR_CODE_ACCESS_DENIED 23
#define ERROR_CODE_INVALID_ACCESS_KEY 24
#define ERROR_CODE_REQUEST_TIME_TOO_SKEWED 25
#define ERROR_CODE_SIGNATURE_DOES_NOT_MATCH 26
#define ERROR_CODE_URL_EXPIRED 27
#define ERROR_CODE_NO_SUCH_BUCKET 28
#define ERROR_CODE_NO_SUCH_KEY 29
#define ERROR_CODE_METHOD_NOT_ALLOWED 30
#define ERROR_CODE_BUCKET_ALREADY_EXISTS 31
#define ERROR_CODE_BUCKET_ALREADY_OWNED_BY_YOU 32
#define ERROR_CODE_BUCKET_NOT_EMPTY 33
#define ERROR_CODE_INVALID_RANGE 34
#define ERROR_CODE_INTERNAL_ERROR 35
#define ERROR_CODE_NOT_IMPLEMENTED 36
#define ERROR_CODE_KEY_TOO_LONG 37


#define ERROR_CODE_UNKNOWN_ERROR_MESSAGE @"未知的错误"
#define ERROR_CODE_BAD_DIGEST_MESSAGE @"错误的摘要"
#define ERROR_CODE_INVALID_ACL_STR_MESSAGE @"ACL配置无效"
#define ERROR_CODE_INVALID_AUTHORIZATION_STR_MESSAGE @"无效的验证字符串"
#define ERROR_CODE_INVALID_BUCKET_NAME_MESSAGE @"无效的Bucket名称"
#define ERROR_CODE_INVALID_DATE_FORMAT_MESSAGE @"无效的日期格式"
#define ERROR_CODE_INVALID_DIGEST_MESSAGE @"无效的摘要"
#define ERROR_CODE_INVALID_ENCYPTION_ALGORITHM_MESSAGE @"无效的指定加密算法"
#define ERROR_CODE_INVALID_HOST_HEADER_MESSAGE @"无效的头信息"
#define ERROR_CODE_INVALID_PARAMETER_MESSAGE @"无效的参数"
#define ERROR_CODE_INVALID_PATH_MESSAGE @"无效的路径"
#define ERROR_CODE_INVALID_QUERY_STR_MESSAGE @"无效的请求字符串"
#define ERROR_CODE_META_DATA_TOO_LARGE_MESSAGE @"metadata过大"
#define ERROR_CODE_MISSING_DATA_HEADER_MESSAGE @"头信息中缺少data"
#define ERROR_CODE_MISSING_HOST_HEADER_MESSAGE @"头信息中缺少host"
#define ERROR_CODE_TOO_MANY_BUCKETS_MESSAGE @"用户的Bucket数目超过限制"
#define ERROR_CODE_BAD_PARAMS_MESSAGE @"参数错误"
#define ERROR_CODE_IMAGE_TYPE_NOT_SUPPORT_MESSAGE @"图片类型不支持"
#define ERROR_CODE_MISSING_FROM_ARGS_MESSAGE @"没有上传Policy"
#define ERROR_CODE_CONTENT_RANGE_ERROR_MESSAGE @"Range错误"
#define ERROR_CODE_CONTENT_LENGTH_OUT_OF_RANGE_MESSAGE @"上传文件内容大于range"
#define ERROR_CODE_POLICY_ERROR_MESSAGE @"Policy错误"
#define ERROR_CODE_EXPIRATION_ERROR_MESSAGE @"Policy中没有expiration"
#define ERROR_CODE_FORM_UNMATCH_POLICY_MESSAGE @"表单中的内容和policy不匹配"
#define ERROR_CODE_ACCESS_DENIED_MESSAGE @"拒绝访问"
#define ERROR_CODE_INVALID_ACCESS_KEY_MESSAGE @"无效的AccessKey"
#define ERROR_CODE_REQUEST_TIME_TOO_SKEWED_MESSAGE @"发起请求的时间和服务器时间超出15分钟"
#define ERROR_CODE_SIGNATURE_DOES_NOT_MATCH_MESSAGE @"签名不匹配"
#define ERROR_CODE_URL_EXPIRED_MESSAGE @"url过期"
#define ERROR_CODE_NO_SUCH_BUCKET_MESSAGE @"该Bucket不存在"
#define ERROR_CODE_NO_SUCH_KEY_MESSAGE @"该Key不存在 "
#define ERROR_CODE_METHOD_NOT_ALLOWED_MESSAGE @"不支持的方法 "
#define ERROR_CODE_BUCKET_ALREADY_EXISTS_MESSAGE @"Bucket已经存在"
#define ERROR_CODE_BUCKET_ALREADY_OWNED_BY_YOU_MESSAGE @"用户已经是Bucket的拥有者"
#define ERROR_CODE_BUCKET_NOT_EMPTY_MESSAGE @"Bucket不为空"
#define ERROR_CODE_INVALID_RANGE_MESSAGE @"无效的range"
#define ERROR_CODE_INTERNAL_ERROR_MESSAGE @"内部错误"
#define ERROR_CODE_NOT_IMPLEMENTED_MESSAGE @"无法处理的方法"
#define ERROR_CODE_KEY_TOO_LONG_MESSAGE @"key太长"
#endif
